### ISSUE TITLE
Startup Page Setting Minor Problems

### ISSUE THREAD

**Issue by TheRealDannyyy** [Armaldio/ttv-desktop-lite#32]
- Applying a new starting page doesn't update the label in settings menu
- Links should also accept "www" for people that copypaste links (https://www.twitch.tv/directory/following)

**Comment by Armaldio** [comment]
Seems fixed

**Comment by TheRealDannyyy** [comment]
Meh, the https requirement is still there but since the most people will copypaste links, it won't matter anyway.
