### ISSUE TITLE
Appbar Unresponsive At Start

### ISSUE THREAD

**Issue by TheRealDannyyy** [Armaldio/ttv-desktop-lite#35]
Clicking the settings element on the appbar causes an error message to appear. CTRL + R fixes the issue.
![error](https://user-images.githubusercontent.com/15656049/41822682-d1c13992-77f3-11e8-9b40-c13f91e2c4be.PNG)

**Comment by TheRealDannyyy** [comment]
Reviewed and works fine now. Closing.

**Comment by TheRealDannyyy** [comment]
Reviewed and works fine now. Closing.

**Comment by Armaldio** [comment]
Don't close, Still broken with a reload

**Comment by TheRealDannyyy** [comment]
Not for me, what reload do you mean exactly?

**Comment by Armaldio** [comment]
Either Ctrl+R or Update in the DOM triggered by a code change

**Comment by TheRealDannyyy** [comment]
Cannot reproduce, reloading works fine on my end.

**Comment by Armaldio** [comment]
Will check later

**Comment by TheRealDannyyy** [comment]
By the way, CTRL+R shouldn't reload everything in the future anyway. (See #33)

**Comment by Armaldio** [comment]
Seems fixed
