### ISSUE TITLE
Twitchy Name Change To "TTV Desktop Lite"?

### ISSUE THREAD

**Issue by TheRealDannyyy** [Armaldio/ttv-desktop-lite#37]
Copyright issues and whatever, name change might be required.
If the change is happening, we need to rename **EVERYTHING** from the ground up with the new name.

_Suggestions are always welcome and can be posted below!_

**Comment by inscaped** [comment]
TTV sounds good so far. Best of luck, guys!

**Comment by TheRealDannyyy** [comment]
My recent commit should include all necessary name changes.  If we find any remaining "Twitchy's", just silently replace them.

Closing.
